[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
chrono = "0.4"
nix = "0.27"
image = "0.24"
winapi = { version = "0.3", features = ["winuser", "windef", "wincon"] }